#ifndef LIBPCDVIEWER_GLOBAL_H
#define LIBPCDVIEWER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBPCDVIEWER_LIBRARY)
#  define LIBPCDVIEWERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBPCDVIEWERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBPCDVIEWER_GLOBAL_H
